FROM ubuntu:18.04

# Setup
RUN apt-get update -y -qq
RUN apt-get install -y locales bash coreutils apt-utils file wget bzip2 git cmake cmake-data ninja-build lsb-release llvm build-essential clang clang-tidy clang-tools -qq

RUN update-alternatives --set cc /usr/bin/clang
RUN update-alternatives --set c++ /usr/bin/clang++

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN locale

RUN mkdir -p /src/
RUN git clone https://github.com/aymara/nind /src/nind

RUN mkdir -p /src/nind/build

# Build
WORKDIR /src/nind/build
RUN cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
RUN ninja package
RUN install -D /src/nind/build/nind-0.1.0-Linux.deb /usr/share/apps/nind/packages/nind-0.1.0-ubuntu18.04.deb

## install github-release to be able to deploy packages
#RUN wget https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 && tar xjf linux-amd64-github-release.tar.bz2 && cp bin/linux/amd64/github-release /usr/bin

